Repository pavanramadass/-Entity-Traffic-Map, pull requests merged in 2021-11, with the labels that each got.

#1 Adding Github Actions to repo
  .github/workflows/godoc_action.yml
Labels: documentation

#20 Initial heatmap generation
  heatmap/heatmap.go
Labels: heatmap

#22 Refactoring of code to use Data struct/class
  detection/data/data.go
  detection/go.mod
  detection/heatmap/heatmap.go
  detection/main.go
  heatmap/heatmap.go
Labels: documentation

#25 Server integration
  index.html
  main.go
  res/calender.js
  res/image/filled.png
  res/image/stock.jpg
  res/script.js
  res/style/main.css
Labels: enhancement

#29 Camera streaming
  index.html
  main.go
Labels: enhancement
